name: flutter_test_extended
description: Adds behavior to flutter_test
version: 0.0.2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  network_image_mock: ^2.1.1

dev_dependencies:
  lints: ^1.0.0
